name: GameUp Api CI/CD Pipeline

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: gameup
          MYSQL_USER: gameup
          MYSQL_PASSWORD: gameup
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests
        run: mvn clean test
        env:
          # Configuration de la datasource pour les tests :
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/gameup?useSSL=false&serverTimezone=UTC
          SPRING_DATASOURCE_USERNAME: gameup
          SPRING_DATASOURCE_PASSWORD: gameup
